### PR TITLE
Created ability to seed initial H2 database on Localhost and fixed github oauth scopes

### PR DESCRIPTION
**Pull request by yinonrousso**
@andrewhlu and I pair programmed to allow the commands in data.sql to run only on locahost instances. We also tweaked the missing github scopes as described in [lab07b](https://ucsb-cs56.github.io/f19/lab/lab07b/#step-11-a-small-fix-to-applicationproperties)

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
@yinonrousso is @andrewhlu on your team?  If so, let's add the label on the F19-Courses label on this so that the team gets credit for the work.

**Comment by yinonrousso** [comment]
@andrewhlu is actually on the F19-Course Tutors team. I was just helping him out last night in open lab hours.

**Comment by andrewhlu** [comment]
I have attached the correct label (F19-Tutors) to this PR. Thanks for the reminder!

**Pull request merged**
